name = "slowlytype"
compatibility_date = "2025-02-26"
compatibility_flags = ["nodejs_compat"]
main = "./worker/index.ts"

[assets]
directory = "./dist/client"
not_found_handling = "none"
binding = "ASSETS"

[images]
binding = "IMAGES"
